title: Detecting Fake Yelp Reviews and Answering User Questions
page.tagline: CS-7641 Machine Learning Course Project 
site.tagline: CS-7641 Machine Learning Course Project 
theme: jekyll-theme-cayman
logo: /assets/yelp_logo.jpeg
mayhjax: True
